service: kin-ad-network

plugins:
  - serverless-plugin-typescript

provider:
  name: aws
  runtime: nodejs12.x
  region: eu-central-1
  stage: ${opt:stage, 'dev'}
  environment:
    REGION: ${self:provider.region}
    CLIENT_TABLE_NAME: ${self:provider.stage}-clients
    EVENTS_TABLE_NAME: ${self:provider.stage}-events
    IRONSOURCE_PRIVATE_KEY: ${self:custom.credentials.IRONSOURCE_PRIVATE_KEY}
  stackPolicy:
    - { Effect: Allow, Principal: "*", Action: "Update:*", Resource: "*"}
    - Effect: Deny
      Principal: "*"
      Action: ["Update:Replace", "Update:Delete"]
      Resource: LogicalResourceId/DynamoDBClientsTable
    - Effect: Deny
      Principal: "*"
      Action: ["Update:Replace", "Update:Delete"]
      Resource: LogicalResourceId/DynamoDBEventsTable
  iamRoleStatements:
    - Effect: Allow
      Action:
      - dynamodb:Query
      Resource:
        - { "Fn::Join" : [ "", [ { "Fn::GetAtt": ["DynamoDBClientsTable", "Arn"] }, "*" ] ] }
    - Effect: Allow
      Action:
      - dynamodb:Query
      - dynamodb:UpdateItem
      Resource:
        - { "Fn::Join" : [ "", [ { "Fn::GetAtt": ["DynamoDBEventsTable", "Arn"] }, "*" ] ] }

custom:
  credentials: ${ssm:/aws/reference/secretsmanager/${self:provider.stage}~true}

functions:
  ironsource_callback:
    handler: handlers/ironsource.default
    events:
      - http:
          path: ironsource
          method: get

resources:
 Resources:
  DynamoDBClientsTable:
    Type: AWS::DynamoDB::Table
    Properties:
      TableName: ${self:provider.stage}-clients
      PointInTimeRecoverySpecification:
        PointInTimeRecoveryEnabled: true
      AttributeDefinitions:
        - AttributeName: "clientId"
          AttributeType: S
      KeySchema:
        - AttributeName: "clientId"
          KeyType: HASH
      BillingMode: PAY_PER_REQUEST

  DynamoDBEventsTable:
    Type: AWS::DynamoDB::Table
    Properties:
      TableName: ${self:provider.stage}-events
      PointInTimeRecoverySpecification:
        PointInTimeRecoveryEnabled: true
      AttributeDefinitions:
        - AttributeName: "clientId"
          AttributeType: S
        - AttributeName: "eventId"
          AttributeType: S
      KeySchema:
        - AttributeName: "clientId"
          KeyType: HASH
        - AttributeName: "eventId"
          KeyType: RANGE
      BillingMode: PAY_PER_REQUEST
